# Generated by Django 4.2.7 on 2023-12-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(default='draft', max_length=10),
        ),
    ]
